ansible_state_path: /home/vagrant/ansible_state
gopath: /vagrant/project/gocode

# Set to True if you have build packages via "make deb" or "make rpm"   
build_packages: False

# https://golang.org/dl/
#go_version: 1.5.3
#go_tarball_checksum: 43afe0c5017e502630b1aea4d44b8a7f059bf60d7f29dfd58db454d4e4e0ae53
go_version: 1.7.3
go_tarball_checksum: 508028aac0654e993564b6e2014bf2d4a9751e3b286661b0b0040046cf18028e
go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"

moira_notifier_repo: https://github.com/moira-alert/notifier.git
moira_cache_repo: https://github.com/moira-alert/cache.git
moira_worker_repo: https://github.com/moira-alert/worker.git
moira_web_repo: https://github.com/moira-alert/web.git

moira_notifier_commit: HEAD
moira_cache_commit: HEAD
moira_worker_commit: HEAD
moira_web_commit: HEAD

moira_notifier_path: "{{ gopath }}/src/github.com/moira-alert/notifier/"
moira_cache_path: "{{ gopath }}/src/github.com/moira-alert/cache/"
moira_web_path: /vagrant/project/moira-web
moira_worker_path: /vagrant/project/moira-worker

overwrite_local_modifications: no

moira_logs: /vagrant/project/log

slack_api_token: 
pushover_api_token:
telegram_api_token:
